-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 21:44:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prod
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prod
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prod` DEFAULT CHARACTER SET utf8 ;
USE `prod` ;

-- -----------------------------------------------------
-- Table `prod`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prod`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prod`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prod`.`friends` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_friends_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_friends_users2_idx` (`friend_id` ASC) VISIBLE,
  CONSTRAINT `fk_friends_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prod`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friends_users2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `prod`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prod`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prod`.`transactions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `friend_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `amount` DOUBLE NOT NULL,
  `amount_after_commission` DOUBLE NOT NULL,
  `commission_amount` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_transactions_users2_idx` (`friend_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `prod`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transactions_users2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `prod`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prod`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prod`.`bank_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `available_balance` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bank_account_users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_bank_account_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `prod`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `prod`.`users` (`id`, `first_name`, `last_name`, `email`, `password`) VALUES (DEFAULT, 'user', 'one', 'user@one.com', '$2a$10$d4ms3/8Mi1cVg.XN6TQ2zO8HpOF0pMLju.q0MQUB6op86jqaSGMlW');
INSERT INTO `prod`.`users` (`id`, `first_name`, `last_name`, `email`, `password`) VALUES (DEFAULT, 'user', 'two', 'user@two.com', '$2a$10$cV.z3ThG5s4gsyB/Cwj5ceUemztSBv3W2olk0NlnFGFaXeIBwScs.');
INSERT INTO `prod`.`users` (`id`, `first_name`, `last_name`, `email`, `password`) VALUES (DEFAULT, 'user', 'three', 'user@three.com', '$2a$10$N2LE5Uktf/3jlogF921.LeGZYZx8r7IncjVSr2gcpvHp4w8XS.Diq');
INSERT INTO `prod`.`users` (`id`, `first_name`, `last_name`, `email`, `password`) VALUES (DEFAULT, 'user', 'four', 'user@four.com', '$2a$10$ZNtIaH6AjcPcUTtReYAMfuauuk/R8AfJBjt4Q5c0E3G1qqzC/dE/i');

INSERT INTO `prod`.`friends` (`id`, `user_id`, `friend_id`) VALUES (DEFAULT, 1, 2);
INSERT INTO `prod`.`friends` (`id`, `user_id`, `friend_id`) VALUES (DEFAULT, 1, 3);
INSERT INTO `prod`.`friends` (`id`, `user_id`, `friend_id`) VALUES (DEFAULT, 2, 3);
INSERT INTO `prod`.`friends` (`id`, `user_id`, `friend_id`) VALUES (DEFAULT, 4, 1);

INSERT INTO `prod`.`transactions` (`id`, `user_id`, `friend_id`, `description`, `amount`, `amount_after_commission`, `commission_amount`) VALUES (DEFAULT, 1, 2, 'description1', 25, 25.13, 0.13);
INSERT INTO `prod`.`transactions` (`id`, `user_id`, `friend_id`, `description`, `amount`, `amount_after_commission`, `commission_amount`) VALUES (DEFAULT, 2, 3, 'description2', 50, 50.25, 0.25);
INSERT INTO `prod`.`transactions` (`id`, `user_id`, `friend_id`, `description`, `amount`, `amount_after_commission`, `commission_amount`) VALUES (DEFAULT, 4, 1, 'description3', 75, 75.38, 0.38);

INSERT INTO `prod`.`bank_account` (`id`, `user_id`, `available_balance`) VALUES (DEFAULT, '1', 149.87);
INSERT INTO `prod`.`bank_account` (`id`, `user_id`, `available_balance`) VALUES (DEFAULT, '2', 174.75);
INSERT INTO `prod`.`bank_account` (`id`, `user_id`, `available_balance`) VALUES (DEFAULT, '3', 350);
INSERT INTO `prod`.`bank_account` (`id`, `user_id`, `available_balance`) VALUES (DEFAULT, '4', 324.62);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
